#!/usr/bin/env bash
# scripts/team/bootstrap_worktree.sh <team_num> [slug]
#
# Creates a team worktree following AQTS conventions:
#   - Path: ../aqts-team<N>-<role>
#   - Branch: team<N>/<slug-or-init-worktree>, based on origin/main
#   - Port offsets: DB=5432+10*N, BACKEND=8000+10*N, etc. written to
#     ../aqts-team<N>-<role>/.env.worktree
#
# Exit codes:
#   0  success
#   2  usage error (bad team number, missing slug, etc.)
#   3  environment error (not in git repo, main missing, worktree exists)
#
# Source of truth for team→role mapping: agent_docs/governance.md §2.
set -euo pipefail

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  sed -n '2,17p' "$0" | sed 's/^# \{0,1\}//'
  exit 0
fi

readonly TEAM_NUM="${1:-}"
readonly SLUG="${2:-init-worktree}"

if [[ ! "${TEAM_NUM}" =~ ^[1-4]$ ]]; then
  echo "ERROR: team number must be 1, 2, 3, or 4 (got: '${TEAM_NUM}')" >&2
  echo "Usage: $0 <team_num> [slug]" >&2
  exit 2
fi

case "${TEAM_NUM}" in
  1) ROLE="strategy" ;;
  2) ROLE="scheduler" ;;
  3) ROLE="api" ;;
  4) ROLE="skills-pilot" ;;
esac

# Lock team 4 worktree creation — ADR-002 Stage 2 Pilot is hands-off until 2026-05-06.
if [[ "${TEAM_NUM}" == "4" ]]; then
  echo "ERROR: team 4 worktree ('aqts-team4-skills-pilot') is reserved for ADR-002 Stage 2 Pilot" >&2
  echo "       and must not be recreated by this script until 2026-05-06." >&2
  echo "       See: agent_docs/governance.md §5, CLAUDE.md §9 (ADR-002 Stage 2)." >&2
  exit 2
fi

readonly REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "${REPO_ROOT}" ]]; then
  echo "ERROR: not inside a git repository" >&2
  exit 3
fi

readonly WT_NAME="aqts-team${TEAM_NUM}-${ROLE}"
readonly WT_PATH="${REPO_ROOT%/*}/${WT_NAME}"
readonly BRANCH_NAME="team${TEAM_NUM}/${SLUG}"

if [[ -e "${WT_PATH}" ]]; then
  echo "ERROR: worktree path already exists: ${WT_PATH}" >&2
  echo "       Use scripts/team/teardown_worktree.sh ${TEAM_NUM} to remove first." >&2
  exit 3
fi

if git show-ref --verify --quiet "refs/heads/${BRANCH_NAME}"; then
  echo "ERROR: branch already exists: ${BRANCH_NAME}" >&2
  echo "       Use a different slug or delete the branch first." >&2
  exit 3
fi

echo "Creating worktree: ${WT_PATH}"
echo "  Branch:  ${BRANCH_NAME}"
echo "  Base:    origin/main (or main fallback)"

if git show-ref --verify --quiet refs/remotes/origin/main; then
  git worktree add "${WT_PATH}" -b "${BRANCH_NAME}" origin/main
else
  git worktree add "${WT_PATH}" -b "${BRANCH_NAME}" main
fi

# Port offset: team1=10, team2=20, team3=30 (team4 locked above).
# docker-compose.yml reads DB_PORT/MONGO_PORT/REDIS_PORT/BACKEND_PORT from .env,
# and .env values can be sourced from .env.worktree via COMPOSE_PROJECT_NAME scoping.
readonly PORT_OFFSET=$((TEAM_NUM * 10))
cat > "${WT_PATH}/.env.worktree" <<EOF
# Generated by scripts/team/bootstrap_worktree.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Source this file before running docker compose up in this worktree:
#   export \$(grep -v '^#' .env.worktree | xargs) && docker compose up -d
# See: docs/operations/claude-multisession-migration-2026-04-22.md §4 (Phase 3)

COMPOSE_PROJECT_NAME=aqts_team${TEAM_NUM}
DB_PORT=$((5432 + PORT_OFFSET))
MONGO_PORT=$((27017 + PORT_OFFSET))
REDIS_PORT=$((6379 + PORT_OFFSET))
BACKEND_PORT=$((8000 + PORT_OFFSET))
EOF

echo ""
echo "✓ Worktree created: ${WT_PATH}"
echo "✓ Port overrides:   .env.worktree (DB:${?}, BACKEND:$((8000 + PORT_OFFSET)), etc.)"
echo ""
echo "Next steps:"
echo "  1. cd ${WT_PATH}"
echo "  2. Open a new terminal/tab and run: claude"
echo "  3. Read team-specific bootstrap: agent_docs/team_prompt_draft.md §${TEAM_NUM}"
echo "  4. Check mailbox SLA: bash scripts/team/mailbox_check_sla.sh ${TEAM_NUM}"
